name: Docker Push

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - run: docker build -t eisenforschung/mpie_stf_visualization_workshop:latest .docker_image/
      - run: docker tag eisenforschung/mpie_stf_visualization_workshop:latest eisenforschung/mpie_stf_visualization_workshop:"$(date +%F)"
      - run: docker images
      - run: docker push eisenforschung/mpie_stf_visualization_workshop:latest
      - run: docker push eisenforschung/mpie_stf_visualization_workshop:"$(date +%F)"