name: Docker Testing

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t eisenforshung/mpie_stf_visualization_workshop:latest .docker_image/
      - run: docker tag eisenforshung/mpie_stf_visualization_workshop:latest eisenforshung/mpie_stf_visualization_workshop:"$(date +%F)"
      - run: docker images
      - run: docker run eisenforshung/mpie_stf_visualization_workshop:latest /bin/bash -c--rm  /bin/bash -c 'source /opt/conda/bin/activate; git clone --recurse-submodules https://github.com/eisenforschung/workshop-experimental-data-visualisation ${HOME}/workshop-experimental-data-visualisation; cd ${HOME}/workshop-experimental-data-visualisation; cp .ci_support/build_notebooks.sh .; chmod +x build_notebooks.sh; ./build_notebooks.sh'  
